"""Long trips are planned in DETAIL a few days at a time (the second, on-demand layer of long-trip planning).

A trip longer than `full_detail_max_days` gets (1) a cheap whole-trip outline (outline.py) and (2) a detailed itinerary for
one chunk of `chunk_days` days at a time, built when the user asks for it. Each chunk is generated by the normal planning
workflow over a small sub-trip (its own dates, area and share of the budget), plus a short text context (where we are in the
trip and what was already planned), so cost per chunk stays flat however long the whole trip is.

Stdlib only.
"""
from __future__ import annotations

from typing import Any, Optional

from app.modules.planning.domain import PlannedItem, PlannedTrip, TripSpec

SUMMARY_TITLES_PER_DAY = 4
SUMMARY_TITLE_CHARS = 42
SUMMARIES_KEPT = 60              # days of summaries stored on the trip
USED_TITLES_KEPT = 80
CONTEXT_DAYS = 7                 # previous days handed to the next chunk's prompt
AVOID_TITLES_SENT = 30
_SKIP_IN_SUMMARY = {"hotel", "transport", "flight"}


class ChunkError(ValueError):
    """The requested chunk does not exist or is not allowed; the message is safe to show the user."""


# --- which days ------------------------------------------------------------------------------------------------------
def chunk_bounds(num_days: int, chunk_days: int) -> list[tuple[int, int]]:
    return [(start, min(start + chunk_days - 1, num_days)) for start in range(1, num_days + 1, chunk_days)]


def resolve_chunk(num_days: int, chunk_days: int, from_day: Optional[int], planned_starts: list[int]) -> tuple[int, int]:
    """The (start_day, end_day) to generate now. `from_day` must be the first day of a chunk; None means "the first chunk
    that is not planned yet"."""
    bounds = chunk_bounds(num_days, chunk_days)
    if from_day is None:
        for start, end in bounds:
            if start not in planned_starts:
                return start, end
        raise ChunkError("Every part of this trip already has a detailed plan.")
    for start, end in bounds:
        if start == from_day:
            return start, end
    raise ChunkError(f"Detailed plans start on days {', '.join(str(s) for s, _ in bounds[:6])}"
                     f"{'...' if len(bounds) > 6 else ''}; day {from_day} is not the start of a part.")


# --- the outline as a map --------------------------------------------------------------------------------------------
def segment_for_day(outline: dict[str, Any], day: int) -> Optional[dict[str, Any]]:
    for seg in outline.get("segments") or []:
        if seg["start_day"] <= day <= seg["end_day"]:
            return seg
    return None


def segments_in_range(outline: dict[str, Any], start_day: int, end_day: int) -> list[dict[str, Any]]:
    return [s for s in outline.get("segments") or [] if s["end_day"] >= start_day and s["start_day"] <= end_day]


def budget_share_for_range(outline: dict[str, Any], start_day: int, end_day: int, total_days: int) -> float:
    """Share of the whole budget that belongs to these days: each segment's share is spread evenly over its own days."""
    total = 0.0
    for seg in segments_in_range(outline, start_day, end_day):
        length = seg["end_day"] - seg["start_day"] + 1
        overlap = min(end_day, seg["end_day"]) - max(start_day, seg["start_day"]) + 1
        total += float(seg.get("budget_share") or 0) * overlap / length
    return total if total > 0 else (end_day - start_day + 1) / max(total_days, 1)


def chunk_spec(spec: TripSpec, outline: dict[str, Any], start_day: int, end_day: int) -> TripSpec:
    """The small sub-trip the normal workflow plans for one chunk."""
    from datetime import timedelta
    seg = segment_for_day(outline, start_day)
    amount = None
    if spec.budget_amount:
        amount = round(spec.budget_amount * budget_share_for_range(outline, start_day, end_day, spec.num_days), 2)
    return TripSpec(
        destination=(seg or {}).get("area") or spec.destination,
        start_date=spec.start_date + timedelta(days=start_day - 1),
        end_date=spec.start_date + timedelta(days=end_day - 1),
        travelers=spec.travelers,
        origin=spec.origin if start_day == 1 else None,
        budget_amount=amount, budget_currency=spec.budget_currency,
    )


# --- context handed to the model for a chunk -------------------------------------------------------------------------
def build_trip_context(outline: dict[str, Any], *, start_day: int, end_day: int, total_days: int) -> dict[str, Any]:
    seg = segment_for_day(outline, start_day) or {}
    previous = segment_for_day(outline, start_day - 1) if start_day > 1 else None
    continuing = bool(previous and previous.get("area") == seg.get("area"))
    summaries = outline.get("summaries") or {}
    recent = [summaries[str(d)] for d in range(max(1, start_day - CONTEXT_DAYS), start_day) if str(d) in summaries]
    in_range = segments_in_range(outline, start_day, end_day)
    rules = [
        f"This is only days {start_day}-{end_day} of a {total_days}-day trip. Plan ONLY the dates given, numbered 1..N, "
        "and stay inside this part's budget.",
        "Do not repeat any place listed in avoid_repeating or already_planned.",
    ]
    if continuing:
        rules.append("The traveller is already staying in this area from the previous days: do NOT add a hotel item.")
    if len(in_range) > 1:
        rules.append("This part crosses into another area (see also_in_range): include the move, and a hotel item on the first day in the new area.")
    return {
        "part": f"days {start_day}-{end_day} of {total_days}",
        "area": seg.get("area"), "theme": seg.get("theme"), "highlights": seg.get("highlights") or [],
        "also_in_range": [{"area": s["area"], "from_day": s["start_day"], "to_day": s["end_day"]} for s in in_range[1:]],
        "continuing_stay": continuing,
        "trip_overview": (outline.get("overview") or "")[:400],
        "already_planned": recent,
        "avoid_repeating": (outline.get("used_titles") or [])[-AVOID_TITLES_SENT:],
        "rules": rules,
    }


# --- remembering what was planned (deterministic, no AI) -------------------------------------------------------------
def _short(text: str) -> str:
    text = " ".join(text.split())
    return text if len(text) <= SUMMARY_TITLE_CHARS else text[: SUMMARY_TITLE_CHARS - 1].rstrip() + "…"


def _notable(items: list[PlannedItem]) -> list[str]:
    return [i.title for i in items if i.item_type not in _SKIP_IN_SUMMARY and i.title]


def record_chunk(outline: dict[str, Any], plan: PlannedTrip, *, start_day: int, day_offset: int) -> dict[str, Any]:
    """A copy of `outline` that notes this chunk as planned and remembers short summaries of its days. `day_offset` is
    start_day - 1 (plan day 1 is trip day start_day)."""
    updated = dict(outline)
    summaries = dict(updated.get("summaries") or {})
    used = list(updated.get("used_titles") or [])
    for day in plan.days:
        titles = _notable(day.items)
        summaries[str(day.day_number + day_offset)] = ("; ".join(_short(t) for t in titles[:SUMMARY_TITLES_PER_DAY]) or "free day")
        used.extend(t for t in titles if t not in used)
    keep = sorted(summaries, key=int)[-SUMMARIES_KEPT:]
    updated["summaries"] = {k: summaries[k] for k in keep}
    updated["used_titles"] = used[-USED_TITLES_KEPT:]
    updated["chunks_planned"] = sorted(set(updated.get("chunks_planned") or []) | {start_day})
    return updated
