"""Attachment endpoints (Master Blueprint §42) — upload, extraction
status, confirm, and trip linking."""
from __future__ import annotations

import asyncio
import uuid
from typing import Optional

from fastapi import APIRouter, Depends, File, Query, UploadFile
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.dependencies import get_current_user, rate_limit, require_feature
from app.core.constants import AttachmentCategory, FeatureFlag
from app.db.models.user import User
from app.db.session import get_db
from app.modules.attachments.schemas import AttachmentLinkTripRequest, AttachmentResponse
from app.modules.attachments.service import AttachmentService

router = APIRouter(prefix="/attachments", tags=["Attachments"])


async def _to_response(attachment) -> AttachmentResponse:
    response = AttachmentResponse.model_validate(attachment)
    return response.model_copy(update={"url": await AttachmentService.fresh_url(attachment)})


@router.post(
    "/upload",
    response_model=AttachmentResponse,
    dependencies=[Depends(require_feature(FeatureFlag.ATTACHMENTS)), Depends(rate_limit(bucket="attachments:upload", max_requests=20, window_seconds=300, per="user"))],
)
async def upload_attachment(
    file: UploadFile = File(...),
    trip_id: Optional[uuid.UUID] = None,
    category: AttachmentCategory = Query(
        default=AttachmentCategory.ATTACHMENT,
        description="`attachment` (booking confirmations etc. — text is extracted) or `travel_document` "
        "(passports, visas, IDs — stored privately and deliberately NOT text-extracted). `trip_pdf` is "
        "generated by the server and cannot be uploaded.",
    ),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Uploads (Supabase Storage, the category's private bucket), then — for
    `attachment` — runs text extraction (pypdf for PDFs, Tesseract OCR for
    images) and heuristic structured-field detection. Optionally links to a
    trip immediately if `trip_id` is provided (membership verified). Every
    upload gets a database row, listed by `GET /attachments`."""
    attachment = await AttachmentService(db).upload_and_process(
        file=file, user_id=current_user.id, trip_id=trip_id, category=category
    )
    return await _to_response(attachment)


@router.get("", response_model=list[AttachmentResponse])
async def list_my_attachments(
    category: Optional[AttachmentCategory] = Query(default=None, description="Only this category."),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    attachments = await AttachmentService(db).list_my_attachments(current_user.id, category=category)
    return list(await asyncio.gather(*[_to_response(a) for a in attachments]))


@router.post("/{attachment_id}/confirm", response_model=AttachmentResponse, dependencies=[Depends(require_feature(FeatureFlag.ATTACHMENTS))])
async def confirm_attachment(
    attachment_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """User confirmation step (Blueprint §42) — marks the extracted
    text/fields as reviewed. Does not itself change the data; it's a
    signal that a human has looked at it."""
    attachment = await AttachmentService(db).confirm(attachment_id=attachment_id, user_id=current_user.id)
    return await _to_response(attachment)


@router.post("/{attachment_id}/link-trip", response_model=AttachmentResponse, dependencies=[Depends(require_feature(FeatureFlag.ATTACHMENTS))])
async def link_attachment_to_trip(
    attachment_id: uuid.UUID,
    payload: AttachmentLinkTripRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    attachment = await AttachmentService(db).link_to_trip(
        attachment_id=attachment_id, user_id=current_user.id, trip_id=payload.trip_id
    )
    return await _to_response(attachment)
