"""
Country reference dataset (Master Prompt §8 localization).

One representative currency / primary language / primary timezone per ISO 3166-1 alpha-2
country code — used to resolve sensible defaults when a user's country is known (from IP,
Accept-Language, or phone region) but their currency/language/timezone are not yet set
explicitly. This is a best-effort default, not a legal or exhaustive statement (many countries
have multiple official languages or timezones; the most common/capital one is used).

Covers 196 countries. A code not in COUNTRIES falls back to the built-in defaults
(USD / en / UTC) in app/utils/localization.py.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CountryInfo:
    name: str
    currency: str    # ISO 4217
    language: str    # ISO 639-1
    timezone: str    # IANA tz name


COUNTRIES: dict[str, CountryInfo] = {
    "AD": CountryInfo(name='Andorra', currency='EUR', language='ca', timezone='Europe/Andorra'),
    "AE": CountryInfo(name='United Arab Emirates', currency='AED', language='ar', timezone='Asia/Dubai'),
    "AF": CountryInfo(name='Afghanistan', currency='AFN', language='fa', timezone='Asia/Kabul'),
    "AG": CountryInfo(name='Antigua and Barbuda', currency='XCD', language='en', timezone='America/Antigua'),
    "AL": CountryInfo(name='Albania', currency='ALL', language='sq', timezone='Europe/Tirane'),
    "AM": CountryInfo(name='Armenia', currency='AMD', language='hy', timezone='Asia/Yerevan'),
    "AO": CountryInfo(name='Angola', currency='AOA', language='pt', timezone='Africa/Luanda'),
    "AR": CountryInfo(name='Argentina', currency='ARS', language='es', timezone='America/Argentina/Buenos_Aires'),
    "AT": CountryInfo(name='Austria', currency='EUR', language='de', timezone='Europe/Vienna'),
    "AU": CountryInfo(name='Australia', currency='AUD', language='en', timezone='Australia/Sydney'),
    "AZ": CountryInfo(name='Azerbaijan', currency='AZN', language='az', timezone='Asia/Baku'),
    "BA": CountryInfo(name='Bosnia and Herzegovina', currency='BAM', language='bs', timezone='Europe/Sarajevo'),
    "BB": CountryInfo(name='Barbados', currency='BBD', language='en', timezone='America/Barbados'),
    "BD": CountryInfo(name='Bangladesh', currency='BDT', language='bn', timezone='Asia/Dhaka'),
    "BE": CountryInfo(name='Belgium', currency='EUR', language='nl', timezone='Europe/Brussels'),
    "BF": CountryInfo(name='Burkina Faso', currency='XOF', language='fr', timezone='Africa/Ouagadougou'),
    "BG": CountryInfo(name='Bulgaria', currency='BGN', language='bg', timezone='Europe/Sofia'),
    "BH": CountryInfo(name='Bahrain', currency='BHD', language='ar', timezone='Asia/Bahrain'),
    "BI": CountryInfo(name='Burundi', currency='BIF', language='fr', timezone='Africa/Bujumbura'),
    "BJ": CountryInfo(name='Benin', currency='XOF', language='fr', timezone='Africa/Porto-Novo'),
    "BN": CountryInfo(name='Brunei', currency='BND', language='ms', timezone='Asia/Brunei'),
    "BO": CountryInfo(name='Bolivia', currency='BOB', language='es', timezone='America/La_Paz'),
    "BR": CountryInfo(name='Brazil', currency='BRL', language='pt', timezone='America/Sao_Paulo'),
    "BS": CountryInfo(name='Bahamas', currency='BSD', language='en', timezone='America/Nassau'),
    "BT": CountryInfo(name='Bhutan', currency='BTN', language='dz', timezone='Asia/Thimphu'),
    "BW": CountryInfo(name='Botswana', currency='BWP', language='en', timezone='Africa/Gaborone'),
    "BY": CountryInfo(name='Belarus', currency='BYN', language='be', timezone='Europe/Minsk'),
    "BZ": CountryInfo(name='Belize', currency='BZD', language='en', timezone='America/Belize'),
    "CA": CountryInfo(name='Canada', currency='CAD', language='en', timezone='America/Toronto'),
    "CD": CountryInfo(name='DR Congo', currency='CDF', language='fr', timezone='Africa/Kinshasa'),
    "CF": CountryInfo(name='Central African Republic', currency='XAF', language='fr', timezone='Africa/Bangui'),
    "CG": CountryInfo(name='Congo', currency='XAF', language='fr', timezone='Africa/Brazzaville'),
    "CH": CountryInfo(name='Switzerland', currency='CHF', language='de', timezone='Europe/Zurich'),
    "CI": CountryInfo(name="Cote d'Ivoire", currency='XOF', language='fr', timezone='Africa/Abidjan'),
    "CL": CountryInfo(name='Chile', currency='CLP', language='es', timezone='America/Santiago'),
    "CM": CountryInfo(name='Cameroon', currency='XAF', language='fr', timezone='Africa/Douala'),
    "CN": CountryInfo(name='China', currency='CNY', language='zh', timezone='Asia/Shanghai'),
    "CO": CountryInfo(name='Colombia', currency='COP', language='es', timezone='America/Bogota'),
    "CR": CountryInfo(name='Costa Rica', currency='CRC', language='es', timezone='America/Costa_Rica'),
    "CU": CountryInfo(name='Cuba', currency='CUP', language='es', timezone='America/Havana'),
    "CV": CountryInfo(name='Cabo Verde', currency='CVE', language='pt', timezone='Atlantic/Cape_Verde'),
    "CY": CountryInfo(name='Cyprus', currency='EUR', language='el', timezone='Asia/Nicosia'),
    "CZ": CountryInfo(name='Czechia', currency='CZK', language='cs', timezone='Europe/Prague'),
    "DE": CountryInfo(name='Germany', currency='EUR', language='de', timezone='Europe/Berlin'),
    "DJ": CountryInfo(name='Djibouti', currency='DJF', language='fr', timezone='Africa/Djibouti'),
    "DK": CountryInfo(name='Denmark', currency='DKK', language='da', timezone='Europe/Copenhagen'),
    "DM": CountryInfo(name='Dominica', currency='XCD', language='en', timezone='America/Dominica'),
    "DO": CountryInfo(name='Dominican Republic', currency='DOP', language='es', timezone='America/Santo_Domingo'),
    "DZ": CountryInfo(name='Algeria', currency='DZD', language='ar', timezone='Africa/Algiers'),
    "EC": CountryInfo(name='Ecuador', currency='USD', language='es', timezone='America/Guayaquil'),
    "EE": CountryInfo(name='Estonia', currency='EUR', language='et', timezone='Europe/Tallinn'),
    "EG": CountryInfo(name='Egypt', currency='EGP', language='ar', timezone='Africa/Cairo'),
    "ER": CountryInfo(name='Eritrea', currency='ERN', language='ti', timezone='Africa/Asmara'),
    "ES": CountryInfo(name='Spain', currency='EUR', language='es', timezone='Europe/Madrid'),
    "ET": CountryInfo(name='Ethiopia', currency='ETB', language='am', timezone='Africa/Addis_Ababa'),
    "FI": CountryInfo(name='Finland', currency='EUR', language='fi', timezone='Europe/Helsinki'),
    "FJ": CountryInfo(name='Fiji', currency='FJD', language='en', timezone='Pacific/Fiji'),
    "FM": CountryInfo(name='Micronesia', currency='USD', language='en', timezone='Pacific/Chuuk'),
    "FR": CountryInfo(name='France', currency='EUR', language='fr', timezone='Europe/Paris'),
    "GA": CountryInfo(name='Gabon', currency='XAF', language='fr', timezone='Africa/Libreville'),
    "GB": CountryInfo(name='United Kingdom', currency='GBP', language='en', timezone='Europe/London'),
    "GD": CountryInfo(name='Grenada', currency='XCD', language='en', timezone='America/Grenada'),
    "GE": CountryInfo(name='Georgia', currency='GEL', language='ka', timezone='Asia/Tbilisi'),
    "GH": CountryInfo(name='Ghana', currency='GHS', language='en', timezone='Africa/Accra'),
    "GM": CountryInfo(name='Gambia', currency='GMD', language='en', timezone='Africa/Banjul'),
    "GN": CountryInfo(name='Guinea', currency='GNF', language='fr', timezone='Africa/Conakry'),
    "GQ": CountryInfo(name='Equatorial Guinea', currency='XAF', language='es', timezone='Africa/Malabo'),
    "GR": CountryInfo(name='Greece', currency='EUR', language='el', timezone='Europe/Athens'),
    "GT": CountryInfo(name='Guatemala', currency='GTQ', language='es', timezone='America/Guatemala'),
    "GW": CountryInfo(name='Guinea-Bissau', currency='XOF', language='pt', timezone='Africa/Bissau'),
    "GY": CountryInfo(name='Guyana', currency='GYD', language='en', timezone='America/Guyana'),
    "HN": CountryInfo(name='Honduras', currency='HNL', language='es', timezone='America/Tegucigalpa'),
    "HR": CountryInfo(name='Croatia', currency='EUR', language='hr', timezone='Europe/Zagreb'),
    "HT": CountryInfo(name='Haiti', currency='HTG', language='fr', timezone='America/Port-au-Prince'),
    "HU": CountryInfo(name='Hungary', currency='HUF', language='hu', timezone='Europe/Budapest'),
    "ID": CountryInfo(name='Indonesia', currency='IDR', language='id', timezone='Asia/Jakarta'),
    "IE": CountryInfo(name='Ireland', currency='EUR', language='en', timezone='Europe/Dublin'),
    "IL": CountryInfo(name='Israel', currency='ILS', language='he', timezone='Asia/Jerusalem'),
    "IN": CountryInfo(name='India', currency='INR', language='hi', timezone='Asia/Kolkata'),
    "IQ": CountryInfo(name='Iraq', currency='IQD', language='ar', timezone='Asia/Baghdad'),
    "IR": CountryInfo(name='Iran', currency='IRR', language='fa', timezone='Asia/Tehran'),
    "IS": CountryInfo(name='Iceland', currency='ISK', language='is', timezone='Atlantic/Reykjavik'),
    "IT": CountryInfo(name='Italy', currency='EUR', language='it', timezone='Europe/Rome'),
    "JM": CountryInfo(name='Jamaica', currency='JMD', language='en', timezone='America/Jamaica'),
    "JO": CountryInfo(name='Jordan', currency='JOD', language='ar', timezone='Asia/Amman'),
    "JP": CountryInfo(name='Japan', currency='JPY', language='ja', timezone='Asia/Tokyo'),
    "KE": CountryInfo(name='Kenya', currency='KES', language='en', timezone='Africa/Nairobi'),
    "KG": CountryInfo(name='Kyrgyzstan', currency='KGS', language='ky', timezone='Asia/Bishkek'),
    "KH": CountryInfo(name='Cambodia', currency='KHR', language='km', timezone='Asia/Phnom_Penh'),
    "KI": CountryInfo(name='Kiribati', currency='AUD', language='en', timezone='Pacific/Tarawa'),
    "KM": CountryInfo(name='Comoros', currency='KMF', language='fr', timezone='Indian/Comoro'),
    "KN": CountryInfo(name='Saint Kitts and Nevis', currency='XCD', language='en', timezone='America/St_Kitts'),
    "KP": CountryInfo(name='North Korea', currency='KPW', language='ko', timezone='Asia/Pyongyang'),
    "KR": CountryInfo(name='South Korea', currency='KRW', language='ko', timezone='Asia/Seoul'),
    "KW": CountryInfo(name='Kuwait', currency='KWD', language='ar', timezone='Asia/Kuwait'),
    "KZ": CountryInfo(name='Kazakhstan', currency='KZT', language='kk', timezone='Asia/Almaty'),
    "LA": CountryInfo(name='Laos', currency='LAK', language='lo', timezone='Asia/Vientiane'),
    "LB": CountryInfo(name='Lebanon', currency='LBP', language='ar', timezone='Asia/Beirut'),
    "LC": CountryInfo(name='Saint Lucia', currency='XCD', language='en', timezone='America/St_Lucia'),
    "LI": CountryInfo(name='Liechtenstein', currency='CHF', language='de', timezone='Europe/Vaduz'),
    "LK": CountryInfo(name='Sri Lanka', currency='LKR', language='si', timezone='Asia/Colombo'),
    "LR": CountryInfo(name='Liberia', currency='LRD', language='en', timezone='Africa/Monrovia'),
    "LS": CountryInfo(name='Lesotho', currency='LSL', language='en', timezone='Africa/Maseru'),
    "LT": CountryInfo(name='Lithuania', currency='EUR', language='lt', timezone='Europe/Vilnius'),
    "LU": CountryInfo(name='Luxembourg', currency='EUR', language='fr', timezone='Europe/Luxembourg'),
    "LV": CountryInfo(name='Latvia', currency='EUR', language='lv', timezone='Europe/Riga'),
    "LY": CountryInfo(name='Libya', currency='LYD', language='ar', timezone='Africa/Tripoli'),
    "MA": CountryInfo(name='Morocco', currency='MAD', language='ar', timezone='Africa/Casablanca'),
    "MC": CountryInfo(name='Monaco', currency='EUR', language='fr', timezone='Europe/Monaco'),
    "MD": CountryInfo(name='Moldova', currency='MDL', language='ro', timezone='Europe/Chisinau'),
    "ME": CountryInfo(name='Montenegro', currency='EUR', language='sr', timezone='Europe/Podgorica'),
    "MG": CountryInfo(name='Madagascar', currency='MGA', language='fr', timezone='Indian/Antananarivo'),
    "MH": CountryInfo(name='Marshall Islands', currency='USD', language='en', timezone='Pacific/Majuro'),
    "MK": CountryInfo(name='North Macedonia', currency='MKD', language='mk', timezone='Europe/Skopje'),
    "ML": CountryInfo(name='Mali', currency='XOF', language='fr', timezone='Africa/Bamako'),
    "MM": CountryInfo(name='Myanmar', currency='MMK', language='my', timezone='Asia/Yangon'),
    "MN": CountryInfo(name='Mongolia', currency='MNT', language='mn', timezone='Asia/Ulaanbaatar'),
    "MR": CountryInfo(name='Mauritania', currency='MRU', language='ar', timezone='Africa/Nouakchott'),
    "MT": CountryInfo(name='Malta', currency='EUR', language='mt', timezone='Europe/Malta'),
    "MU": CountryInfo(name='Mauritius', currency='MUR', language='en', timezone='Indian/Mauritius'),
    "MV": CountryInfo(name='Maldives', currency='MVR', language='dv', timezone='Indian/Maldives'),
    "MW": CountryInfo(name='Malawi', currency='MWK', language='en', timezone='Africa/Blantyre'),
    "MX": CountryInfo(name='Mexico', currency='MXN', language='es', timezone='America/Mexico_City'),
    "MY": CountryInfo(name='Malaysia', currency='MYR', language='ms', timezone='Asia/Kuala_Lumpur'),
    "MZ": CountryInfo(name='Mozambique', currency='MZN', language='pt', timezone='Africa/Maputo'),
    "NA": CountryInfo(name='Namibia', currency='NAD', language='en', timezone='Africa/Windhoek'),
    "NE": CountryInfo(name='Niger', currency='XOF', language='fr', timezone='Africa/Niamey'),
    "NG": CountryInfo(name='Nigeria', currency='NGN', language='en', timezone='Africa/Lagos'),
    "NI": CountryInfo(name='Nicaragua', currency='NIO', language='es', timezone='America/Managua'),
    "NL": CountryInfo(name='Netherlands', currency='EUR', language='nl', timezone='Europe/Amsterdam'),
    "NO": CountryInfo(name='Norway', currency='NOK', language='no', timezone='Europe/Oslo'),
    "NP": CountryInfo(name='Nepal', currency='NPR', language='ne', timezone='Asia/Kathmandu'),
    "NR": CountryInfo(name='Nauru', currency='AUD', language='en', timezone='Pacific/Nauru'),
    "NZ": CountryInfo(name='New Zealand', currency='NZD', language='en', timezone='Pacific/Auckland'),
    "OM": CountryInfo(name='Oman', currency='OMR', language='ar', timezone='Asia/Muscat'),
    "PA": CountryInfo(name='Panama', currency='PAB', language='es', timezone='America/Panama'),
    "PE": CountryInfo(name='Peru', currency='PEN', language='es', timezone='America/Lima'),
    "PG": CountryInfo(name='Papua New Guinea', currency='PGK', language='en', timezone='Pacific/Port_Moresby'),
    "PH": CountryInfo(name='Philippines', currency='PHP', language='en', timezone='Asia/Manila'),
    "PK": CountryInfo(name='Pakistan', currency='PKR', language='ur', timezone='Asia/Karachi'),
    "PL": CountryInfo(name='Poland', currency='PLN', language='pl', timezone='Europe/Warsaw'),
    "PS": CountryInfo(name='Palestine', currency='ILS', language='ar', timezone='Asia/Gaza'),
    "PT": CountryInfo(name='Portugal', currency='EUR', language='pt', timezone='Europe/Lisbon'),
    "PW": CountryInfo(name='Palau', currency='USD', language='en', timezone='Pacific/Palau'),
    "PY": CountryInfo(name='Paraguay', currency='PYG', language='es', timezone='America/Asuncion'),
    "QA": CountryInfo(name='Qatar', currency='QAR', language='ar', timezone='Asia/Qatar'),
    "RO": CountryInfo(name='Romania', currency='RON', language='ro', timezone='Europe/Bucharest'),
    "RS": CountryInfo(name='Serbia', currency='RSD', language='sr', timezone='Europe/Belgrade'),
    "RU": CountryInfo(name='Russia', currency='RUB', language='ru', timezone='Europe/Moscow'),
    "RW": CountryInfo(name='Rwanda', currency='RWF', language='rw', timezone='Africa/Kigali'),
    "SA": CountryInfo(name='Saudi Arabia', currency='SAR', language='ar', timezone='Asia/Riyadh'),
    "SB": CountryInfo(name='Solomon Islands', currency='SBD', language='en', timezone='Pacific/Guadalcanal'),
    "SC": CountryInfo(name='Seychelles', currency='SCR', language='fr', timezone='Indian/Mahe'),
    "SD": CountryInfo(name='Sudan', currency='SDG', language='ar', timezone='Africa/Khartoum'),
    "SE": CountryInfo(name='Sweden', currency='SEK', language='sv', timezone='Europe/Stockholm'),
    "SG": CountryInfo(name='Singapore', currency='SGD', language='en', timezone='Asia/Singapore'),
    "SI": CountryInfo(name='Slovenia', currency='EUR', language='sl', timezone='Europe/Ljubljana'),
    "SK": CountryInfo(name='Slovakia', currency='EUR', language='sk', timezone='Europe/Bratislava'),
    "SL": CountryInfo(name='Sierra Leone', currency='SLE', language='en', timezone='Africa/Freetown'),
    "SM": CountryInfo(name='San Marino', currency='EUR', language='it', timezone='Europe/San_Marino'),
    "SN": CountryInfo(name='Senegal', currency='XOF', language='fr', timezone='Africa/Dakar'),
    "SO": CountryInfo(name='Somalia', currency='SOS', language='so', timezone='Africa/Mogadishu'),
    "SR": CountryInfo(name='Suriname', currency='SRD', language='nl', timezone='America/Paramaribo'),
    "SS": CountryInfo(name='South Sudan', currency='SSP', language='en', timezone='Africa/Juba'),
    "ST": CountryInfo(name='Sao Tome and Principe', currency='STN', language='pt', timezone='Africa/Sao_Tome'),
    "SV": CountryInfo(name='El Salvador', currency='USD', language='es', timezone='America/El_Salvador'),
    "SY": CountryInfo(name='Syria', currency='SYP', language='ar', timezone='Asia/Damascus'),
    "SZ": CountryInfo(name='Eswatini', currency='SZL', language='en', timezone='Africa/Mbabane'),
    "TD": CountryInfo(name='Chad', currency='XAF', language='fr', timezone='Africa/Ndjamena'),
    "TG": CountryInfo(name='Togo', currency='XOF', language='fr', timezone='Africa/Lome'),
    "TH": CountryInfo(name='Thailand', currency='THB', language='th', timezone='Asia/Bangkok'),
    "TJ": CountryInfo(name='Tajikistan', currency='TJS', language='tg', timezone='Asia/Dushanbe'),
    "TL": CountryInfo(name='Timor-Leste', currency='USD', language='pt', timezone='Asia/Dili'),
    "TM": CountryInfo(name='Turkmenistan', currency='TMT', language='tk', timezone='Asia/Ashgabat'),
    "TN": CountryInfo(name='Tunisia', currency='TND', language='ar', timezone='Africa/Tunis'),
    "TO": CountryInfo(name='Tonga', currency='TOP', language='en', timezone='Pacific/Tongatapu'),
    "TR": CountryInfo(name='Turkey', currency='TRY', language='tr', timezone='Europe/Istanbul'),
    "TT": CountryInfo(name='Trinidad and Tobago', currency='TTD', language='en', timezone='America/Port_of_Spain'),
    "TV": CountryInfo(name='Tuvalu', currency='AUD', language='en', timezone='Pacific/Funafuti'),
    "TW": CountryInfo(name='Taiwan', currency='TWD', language='zh', timezone='Asia/Taipei'),
    "TZ": CountryInfo(name='Tanzania', currency='TZS', language='sw', timezone='Africa/Dar_es_Salaam'),
    "UA": CountryInfo(name='Ukraine', currency='UAH', language='uk', timezone='Europe/Kyiv'),
    "UG": CountryInfo(name='Uganda', currency='UGX', language='en', timezone='Africa/Kampala'),
    "US": CountryInfo(name='United States', currency='USD', language='en', timezone='America/New_York'),
    "UY": CountryInfo(name='Uruguay', currency='UYU', language='es', timezone='America/Montevideo'),
    "UZ": CountryInfo(name='Uzbekistan', currency='UZS', language='uz', timezone='Asia/Tashkent'),
    "VA": CountryInfo(name='Vatican City', currency='EUR', language='it', timezone='Europe/Vatican'),
    "VC": CountryInfo(name='Saint Vincent and the Grenadines', currency='XCD', language='en', timezone='America/St_Vincent'),
    "VE": CountryInfo(name='Venezuela', currency='VES', language='es', timezone='America/Caracas'),
    "VN": CountryInfo(name='Vietnam', currency='VND', language='vi', timezone='Asia/Ho_Chi_Minh'),
    "VU": CountryInfo(name='Vanuatu', currency='VUV', language='en', timezone='Pacific/Efate'),
    "WS": CountryInfo(name='Samoa', currency='WST', language='sm', timezone='Pacific/Apia'),
    "YE": CountryInfo(name='Yemen', currency='YER', language='ar', timezone='Asia/Aden'),
    "ZA": CountryInfo(name='South Africa', currency='ZAR', language='en', timezone='Africa/Johannesburg'),
    "ZM": CountryInfo(name='Zambia', currency='ZMW', language='en', timezone='Africa/Lusaka'),
    "ZW": CountryInfo(name='Zimbabwe', currency='ZWL', language='en', timezone='Africa/Harare'),
}


def get_country(code: str) -> "CountryInfo | None":
    return COUNTRIES.get((code or "").strip().upper())
